# Generated by Django 5.1.2 on 2024-10-23 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_dvd_alter_borrowing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 11, 7, 54, 640708, tzinfo=datetime.timezone.utc)),
        ),
    ]
