# Generated by Django 5.1.2 on 2024-10-23 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_category_alter_borrowing_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'Jeu de plateau'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livre'},
        ),
        migrations.AlterModelOptions(
            name='borrowing',
            options={'verbose_name': 'Emprunt'},
        ),
        migrations.AlterModelOptions(
            name='cd',
            options={'verbose_name_plural': 'Cd'},
        ),
        migrations.AlterModelOptions(
            name='dvd',
            options={'verbose_name_plural': 'Dvd'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media'},
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 12, 37, 34, 410453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
