# Generated by Django 5.1.2 on 2024-10-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('book', 'Livre'), ('Dvd', 'Film'), ('Cd', 'Musique'), ('board_game', 'Jeu de société')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nb_borrow', models.IntegerField(default=0)),
                ('has_overdue', models.BooleanField(default=False)),
                ('can_borrow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.media')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.member')),
            ],
            options={
                'verbose_name': 'Emprunt',
            },
        ),
    ]
